version: '3'

volumes:
  grafana_data: {}
  mqtt_data: {}
  mqtt_log: {}
  telegraf_conf:
    driver: local
    driver_opts:
      type: none
      device: /Users/robert/data/ppm/conf
      o: bind
  ppm_tag:
    driver: local
    driver_opts:
      type: none
      device: /Users/robert/data/ppm/tag
      o: bind
networks:
  video_net:
  iot_net:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    restart: unless-stopped
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - 1880:1880
    env_file: 
      - .env
    environment:
      - TZ=Asia/Taipei
    volumes:
      - mqtt_log:/mosquitto/log:rw
      - mqtt_data:/mosquitto/data:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mqtt.pwd:/mosquitto/config/mqtt.pwd
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    networks:
      - iot_net
  
  nginx:
    image: roberthu1006/gateway-nginx:0.0.1
    container_name: nginx
    hostname: nginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 1883:1883
      - 8883:8883
    environment:
      - TZ=Asia/Taipei  
    networks:
      - video_net
      - iot_net
    depends_on:
      - mosquitto
      - streamer
  
  telegraf:
    image: telegraf:1.32.0
    restart: always
    container_name: telegraf
    hostname: telegraf
    ports:
      - 9273:9273
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - telegraf_conf:/etc/telegraf/conf/
      - ppm_tag:/etc/telegraf/tag
    depends_on:
      - mosquitto
      - streamer
    command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/conf/
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
    networks:
      - iot_net
    
  streamer:
    image: roberthu1006/gateway-streamer:0.0.1
    build:
      context: ./streamer
      dockerfile: Dockerfile
    container_name: streamer
    hostname: streamer
    restart: always
    # 每棟樓或一個subnet 一台gateway及一個代碼
    environment:
      - TZ=Asia/Taipei
    env_file: 
      - .env
    ports:
      - 3010:3010
      - 9274:8010
    volumes:
      - telegraf_conf:/etc/telegraf/conf
      - ppm_tag:/etc/telegraf/tag
    networks:
      - video_net


  