global:
  scrape_interval: 3s
  evaluation_interval: 5s

#rule_files:
#  - rules/alert_rules.yml

scrape_configs:
  - job_name: "telegraf"
    scrape_interval: 2s
    static_configs:
      - targets: ["telegraf:9273"]

  #- job_name: "cadvisor"
  #  static_configs:
  #  - targets: ["cadvisor:8080"]
  #  metrics_path: '/metrics'

