apiVersion: 1
datasources:
  # org 1 ---------
  - name: Prometheus
    type: prometheus
    uid: ppm_prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    #password: <string>
    #user: <string>
    #database: <string>
    #basicAuth: true
    #basicAuthUser: $API_USER
    #basicAuthPassword: $API_PASSWORD
    withCredentials:
    isDefault:
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true

  