{
 "title": "警報處理",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Domain", "query": "GET domain" },
   {
    "name": "ID",
    "query": "HMGET ${__user.login}@${__org.name} id"
   },
   {
    "name": "Verify_ID",
    "query": "SELECT tc FROM alert_db.dashboard\nWHERE item = \"D2\""
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n  <tbody>\n    <tr>\n      <td class=\"border_td\" style=\"width: 60%; border: rgb(0, 0, 0);\" rowspan=\"6\">\n        <span style=\"font-size: 28px;\">{{chinese}}</span></td>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/{{alarm_type}}.svg\" width=\"24px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n        {{#if (eq alarm_priority \"Critical\")}}\n      <td style=\"width: 30%; border:0;\"><span style=\"background-color: rgb(200, 0, 0);\">{{alarm_priority}}</span></td>\n      {{/if}}\n      {{#if (eq alarm_priority \"High\")}}\n      <td style=\"width: 30%; border:0;\"><span style=\"background-color: rgb(230, 120, 50);\">{{alarm_priority}}</span>\n      </td>\n      {{/if}}\n      {{#if (eq alarm_priority \"Medium\")}}\n      <td style=\"width: 30%; border:0;\"><span style=\"background-color: rgb(230, 230, 50);\">{{alarm_priority}}</span>\n      </td>\n      {{/if}}\n      </td>\n    </tr>\n    <tr>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/iot.png\" width=\"20px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">{{device_name}}</td>\n    </tr>\n    <tr>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/calendar.png\" width=\"18px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n        {{date TT \"YYYY-MM-DD\"}}\n      </td>\n    </tr>\n    <tr>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/clock.png\" width=\"20px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n        {{date TT \"HH:mm:ss\"}}<br></td>\n    </tr>\n    <tr>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/floor.png\" width=\"20px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n        {{floor}}<br>\n      </td>\n    </tr>\n    <tr>\n      <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n        <img src=\"/public/img/icon/area.png\" width=\"16px\"><br>\n      </td>\n      <td style=\"width: 30%; border: rgb(0, 0, 0);\">{{area}}</td>\n    </tr>\n  </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT *, date_sub(start_time, interval +8 hour) TT \nFROM alert_db.alert_table as A\nleft join\n(SELECT chinese, property_code  FROM alert_db.map_table ) as M\non M.property_code = A.code\nWHERE incidentID = \"${ID}\"\n\n"
    }
   ]
  },
  {
   "title": "確認警報",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.progress_table\nWHERE incidentID = \"${ID}\" \nAND stage = 1"
    }
   ]
  },
  {
   "title": "標準作業程序",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT pdf FROM alert_db.SOP\nWHERE sop_id = (SELECT SOP FROM alert_db.alert_table \nWHERE incidentID = \"${ID}\")"
    }
   ]
  },
  {
   "title": "通知現場工作人員",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 4 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.progress_table\nWHERE incidentID = \"${ID}\" \nAND stage = 2"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 5 },
   "options": {
    "content": "<table style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 80%; border: rgb(0, 0, 0);\" colspan=\"4\">\n                {{#if (eq stage 0)}}\n                <img src=\"/public/img/icon/New_Alarm.svg\" width=\"120px\"><br>\n                {{/if}}\n                {{#if (eq stage 1)}}\n                <img src=\"/public/img/icon/Alarm_Acknowledged.svg\" width=\"120px\"><br>\n                {{/if}}\n                {{#if (eq stage 2)}}\n                <img src=\"/public/img/icon/Site_Staff_Informed.svg\" width=\"120px\"><br>\n                {{/if}}\n                {{#if (eq stage 3)}}\n                <img src=\"/public/img/icon/Site_Staff_Response.svg\" width=\"120px\"><br>\n                {{/if}}\n                {{#if (eq stage 4)}}\n                <img src=\"/public/img/icon/Site_Staff_Report.svg\" width=\"120px\"><br>\n                {{/if}}\n                {{#if (eq stage 5)}}\n                <img src=\"/public/img/icon/Alarm_Closed.svg\" width=\"120px\"><br>\n                {{/if}}\n            </td>\n            <td style=\"width: 20%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"3\">\n                {{#if (eq log_time null)}}\n                <img src=\" /public/img/icon/default.svg\" width=\"32px\"><br>\n            {{else}}\n                <img src=\"/public/img/icon/press.svg\" width=\"32px\"><br>\n            {{/if}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/log_time.png\" width=\"18px\"><br>\n            </td>\n            <td style=\"text-align: left; width: 30%; border: rgb(0, 0, 0);\">\n                {{#if (eq log_time null)}}\n                {{else}}\n                {{date TT \"HH:mm:ss\"}}\n                {{/if}}\n            </td>\n            <td style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/log_user.png\" width=\"18px\"><br>\n            </td>\n            <td style=\"text-align: left; width: 30%; border: rgb(0, 0, 0);\">{{user}}<br></td>\n        </tr>\n        <tr>\n            <td style=\"width: 80%; border: rgb(0, 0, 0);\" colspan=\"4\">{{log_content}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT *, date_sub(log_time, interval +8 hour) TT  FROM alert_db.progress_table \nWHERE incidentID = \"${ID}\" "
    }
   ]
  },
  {
   "title": "現場工作人員回應",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.progress_table\nWHERE incidentID = \"${ID}\" \nAND stage = 3"
    }
   ]
  },
  {
   "title": "現場工作人員報告",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 13 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.progress_table\nWHERE incidentID = \"${ID}\" \nAND stage = 4"
    }
   ]
  },
  {
   "title": "警報結案",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 17 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.progress_table\nWHERE incidentID = \"${ID}\" \nAND stage = 5"
    }
   ]
  }
 ]
}