{
 "title": "警報驗證",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   {
    "name": "ID",
    "query": "HMGET ${__user.login}@${__org.name} id"
   },
   {
    "name": "Code",
    "query": "HMGET ${__user.login}@${__org.name} site"
   },
   {
    "name": "Floor",
    "query": "SELECT floor FROM alert_db.alert_table where incidentID = \"${ID}\""
   },
   {
    "name": "image_id",
    "query": "SELECT alarm_image FROM alert_db.alert_table where incidentID = \"${ID}\""
   },
   {
    "name": "Fingerprint",
    "query": "SELECT fingerprint FROM alert_db.alert_table where incidentID = \"${ID}\""
   },
   {
    "name": "X",
    "query": "SELECT X FROM alert_db.alert_table where incidentID = \"${ID}\""
   },
   {
    "name": "Y",
    "query": "SELECT Y FROM alert_db.alert_table where incidentID = \"${ID}\""
   },
   { "name": "Domain", "query": "GET domain" },
   {
    "name": "Handle_ID",
    "query": "SELECT tc FROM alert_db.dashboard\nWHERE item = \"D3\""
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "options": {
    "content": "<table style=\"width: 100%; padding: 0px; border-spacing: 0px; border-collapse: separate; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 100%; border: rgb(0, 0, 0); padding: 0px; text-align: center;\" colspan=\"4\"><span style=\"font-size: 28px;\">{{chinese}}</span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; border: rgb(0, 0, 0); padding: 0px;\"><img src=\"/public/img/icon/user.png\" style=\"width: 18px;\"></td>\n            <td style=\"width: 85%; border: rgb(0, 0, 0); padding: 0px;\" colspan=\"3\">{{contact}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; border: rgb(0, 0, 0); padding: 0px;\"><img src=\"/public/img/icon/phone.png\" style=\"width: 18px;\"></td>\n            <td style=\"width: 35%; border: rgb(0, 0, 0); padding: 0px;\">{{telno1}}</td>\n            <td style=\"width: 15%; border: rgb(0, 0, 0); padding: 0px;\"><img src=\"/public/img/icon/phone.png\" style=\"width: 18px;\"></td>\n            <td style=\"width: 35%; border: rgb(0, 0, 0); padding: 0px;\">{{telno2}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT chinese, contact, telno1, telno2 FROM alert_db.map_table \nWHERE property_code = \"${Code}\""
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 12, "w": 11, "x": 6, "y": 0 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td class=\"border_td\" style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/{{alarm_type}}.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\">警報類別</span>\n            </td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\" rowspan=\"2\">\n                <img src=\"/public/img/icon/alarm.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100);\">警報特性</span>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{alarm_type}}</td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">\n                {{#if (eq rssi \"false\")}}\n                <img src=\"/public/img/icon/test.svg\" width=\"80px\"><br>\n                {{else}}\n                <img src=\"/public/img/icon/real.svg\" width=\"80px\"><br>\n                {{/if}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/calender.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\">警報時間</span>\n            </td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\" rowspan=\"2\">\n                <img src=\"/public/img/icon/Area_of_Interest.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100);\">關注區域</span>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{date TT 'YYYY-MM-DD HH:mm:ss'}}</td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">\n                {{area}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/Sensor_Source.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\">感測器名稱</span>\n            </td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\" rowspan=\"4\">\n                <img src=\"/public/img/icon/view.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\" rowspan=\"4\">\n                <img src=\"/public/img/floorplan/{{code}}/{{area}}.jpg\" onerror=\"this.src='/public/img/icon/image-err.svg'\" width:\"200px\" height=\"112px\">\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{device_name}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/Alarm_Priority.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\">優先等級</span>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{alarm_priority}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/Alarm_Group.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100);\">感測訊息供應商</span>\n            </td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\" rowspan=\"4\">\n                <img src=\"/public/img/icon/snapshot.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\" rowspan=\"4\">\n                {{#if (eq cam_link \"na\")}}\n                <img src=\"/public/img/floorplan/{{code}}/{{device_name}}.jpg\" onerror=\"this.src='/public/img/icon/image-err.svg'\"  width:\"200\" height=\"112px\">\n                {{else}}\n                <img src=\"/public/img/capture/{{alarm_image}}.jpg\" onerror=\"this.src='/public/img/icon/image-err.svg'\" width:\"200px\" height=\"112px\">\n                {{/if}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 16.2641%; border: rgb(0, 0, 0);\">{{alarm_group}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0); text-align: right;\" rowspan=\"2\">\n                <img src=\"/public/img/icon/Alarm_Floor.svg\" width=\"24px\" height=\"24px\"><br>\n            </td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\">樓層</span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{floor}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; border: rgb(0, 0, 0);\"><br></td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\"><br></td>\n            <td style=\"width: 50%; text-align: center; border: rgb(0, 0, 0);\" colspan=\"2\">\n                {{#if (eq incidentID null)}}\n                <img src=\" /public/img/icon/create-g.svg\" width=\"110px\"><br>\n                {{else}}\n                <a href=\"https://{{variableValue '${Domain}'}}/d/{{variableValue '${Handle_ID}'}}?orgId={{variableValue '${__org.id}'}}?&var-ID={{incidentID}}\">\n                    <img src=\" /public/img/icon/create-b.svg\" width=\"110px\"><br></a>\n                {{/if}}\n            </td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT *, date_sub(start_time, interval +8 hour) TT FROM alert_db.alert_table \nWHERE incidentID = \"${ID}\" "
    }
   ]
  },
  {
   "title": "警報樓層 : ${Floor}",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "dataset": "alert_db" }
   ]
  },
  {
   "title": "警報列表",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 3 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\"><img src=\"/public/img/icon/{{alarm_type}}.svg\" style=\"height: 22px;\"></td>\n            <td style=\"width: 35%; border: rgb(0, 0, 0);\">{{alarm_type}}</td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\"><img src=\"/public/img/icon/clock.svg\" style=\"height: 18px;\"></td>\n            <td style=\"width: 15%; border: rgb(0, 0, 0);\">{{date TT 'HH:mm:ss'}}</td>\n            <td style=\"width: 15%; border: rgb(0, 0, 0); vertical-align: right; text-align: right;\">\n                {{#if (eq (variableValue '${ID}') incidentID)}}\n                    <img src=\"/public/img/icon/check-o-green.svg\" width=\"26px\" height=\"32px\"><br>\n                \n                {{else}}\n                    <a href=\"http://{{variableValue '${Domain}'}}/api/savills/dashboard?login={{variable '{__user.login}'}}@{{variable '{__org.name}'}}&code={{variableValue '${Code}'}}&alarm={{incidentID}}\">\n                    <img src=\"/public/img/icon/check-o-gray.svg\" width=\"26px\" height=\"32px\"></a><br>    \n                {{/if}}\n            </td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT *, date_sub(start_time, interval +8 hour) TT FROM alert_db.alert_table AS A \nWHERE code = \"${Code}\" \nAND progress < 2\nORDER BY start_time desc"
    }
   ]
  },
  {
   "title": "警報處理狀況",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 12 },
   "options": {
    "content": "{{#each data}}\n<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td class=\"border_td\" style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\">\n                {{#if (eq TT null)}}\n                    <img src=\"/public/img/icon/notyet.svg\" width=\"36px\"><br>\n                {{else}}\n                    <img src=\"/public/img/icon/done.svg\" width=\"36px\"><br>\n                {{/if}}\n            </td>\n            <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n                {{#if (eq stage 0)}}New Alarm{{/if}}\n                {{#if (eq stage 1)}}Alarm Notified{{/if}}\n                {{#if (eq stage 2)}}Alarm Verified{{/if}}\n                {{#if (eq stage 3)}}Alarm In Process{{/if}}\n                {{#if (eq stage 4)}}Alarm Completed{{/if}}\n                {{#if (eq stage 5)}}Alarm Closed{{/if}}\n            </td>\n            <td style=\"width: 8%; text-align: right; border: rgb(0, 0, 0);\">\n                {{#if (eq log_time null)}}{{else}}\n                    <img src=\"/public/img/icon/calendar.svg\" width=\"18px\"><br>\n                {{/if}}\n            </td>\n            <td style=\"width: 22%; border: rgb(0, 0, 0);\">\n                {{#if (eq TT null)}}{{else}}\n                    {{date TT \"YYYY-MM-DD\"}}\n                {{/if}}\n            </td>\n            <td style=\"width: 8%; text-align: right; border: rgb(0, 0, 0);\">\n                {{#if (eq TT null)}}{{else}}\n                    <img src=\"/public/img/icon/clock.svg\" width=\"18px\"><br>\n                {{/if}}\n            </td>\n            <td style=\"width: 22%; border: rgb(0, 0, 0);\">\n                {{#if (eq TT null)}}{{else}}\n                    {{date TT \"HH:mm:ss\"}}\n                {{/if}}\n            </td>\n        </tr>\n    </tbody>\n</table>\n{{/each}}"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * , date_sub(log_time, interval +8 hour) TT FROM alert_db.progress_table \nWHERE incidentID = \"${ID}\" "
    }
   ]
  },
  {
   "title": "警報歷史紀錄",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 12 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT start_time FROM alert_db.alert_table \nwhere fingerprint = \"${Fingerprint}\" and progress = 3"
    }
   ]
  },
  {
   "title": "警報視頻",
   "type": "text",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "options": {
    "content": "<video\n      controls\n      loop\n      autoplay\n      src=\"/public/img/capture/${image_id}.mp4\"\n      width=\"100%\"\n      poster=\"benefits-of-coding.jpg\"\n></video>\n"
   }
  }
 ]
}