{
 "title": "Configurator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "User" },
   { "name": "Role" },
   { "name": "SensorID" },
   {
    "name": "Sensor",
    "label": "sensor",
    "query": "SELECT sensorName FROM alert_db.device_table where deviceID = \"${SensorID}\""
   },
   { "name": "Domain", "query": "GET domain" },
   {
    "name": "Team",
    "query": "HGET ${__user.login}@${__org.name} team"
   },
   {
    "name": "Building",
    "query": "SELECT english FROM alert_db.map_table WHERE  team = \"${Team}\""
   },
   {
    "name": "Code",
    "query": "SELECT property_code FROM alert_db.map_table where english in (${Building:doublequote});"
   },
   {
    "name": "Floor",
    "query": "SELECT DISTINCT floor FROM alert_db.device_table where propertyCode in (${Code:doublequote})"
   },
   {
    "name": "Area",
    "query": "SELECT area FROM alert_db.device_table where deviceID = \"${SensorID}\""
   },
   { "name": "Key" }
  ]
 },
 "panels": [
  {
   "title": "IoT Sensor Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.device_table\nWHERE category = \"iot\""
    }
   ]
  },
  {
   "title": "Camera Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.device_table\nWHERE category = \"cam\""
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.message_table"
    }
   ]
  },
  {
   "title": "Message Type Distribution",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%;\">\n    <tbody>\n        <tr>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Water_Leakage.svg\" width=\"22px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Water Leakage</td>\n            <td style=\"width: 10%;\">{{Water_Leakage}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Temperature_Humidity.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Temp. Humidity</td>\n            <td style=\"width: 10%;\">{{Temperature_Humidity}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Loitering_Detected.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Loitering Detected</td>\n            <td style=\"width: 10%;\">{{Loitering_Detected}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Battery_Low.svg\" height=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Battery Low</td>\n            <td style=\"width: 10%;\">{{Battery_Low}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/FCP_Alarm.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18;\">FCP Alarm</td>\n            <td style=\"width: 10%;\">{{FCP_Alarm}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Intrusion_Detected.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Intrusion Detected</td>\n            <td style=\"width: 10%;\">{{Intrusion_Detected}}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Sensor_Disconnect.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Disconnected</td>\n            <td style=\"width: 10%;\">{{Sensor_Disconnect}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/Door_Contact.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Door Contact</td>\n            <td style=\"width: 10%;\">{{Door_Contact}}</td>\n            <td style=\"width: 5%; text-align: center;\">\n                <img src=\"/public/img/icon/FallDown_Detected.svg\" width=\"20px\"><br>\n            </td>\n            <td style=\"width: 18%;\">Falldown Detected</td>\n            <td style=\"width: 10%;\">{{FallDown_Detected}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "select\n\tSUM(CASE WHEN messageType = 'Water_Leakage' THEN 1 END) AS Water_Leakage,\n    SUM(CASE WHEN messageType = 'Temperature_Humidity' THEN 1 END) AS Temperature_Humidity,\n    SUM(CASE WHEN messageType = 'Battery_Low' THEN 1 END) AS Battery_Low,\n    SUM(CASE WHEN messageType = 'Sensor_Disconnect' THEN 1 END) AS Sensor_Disconnect,\n    SUM(CASE WHEN messageType = 'Loitering_Detected' THEN 1 END) AS Loitering_Detected,\n    SUM(CASE WHEN messageType = 'Intrusion_Detected' THEN 1 END) AS Intrusion_Detected,\n    SUM(CASE WHEN messageType = 'FallDown_Detected' THEN 1 END) AS FallDown_Detected,\n    SUM(CASE WHEN messageType = 'FCP_Alarm' THEN 1 END) AS FCP_Alarm,\n    SUM(CASE WHEN messageType = 'Door_Contact' THEN 1 END) AS Door_Contact\nfrom alert_db.message_table"
    }
   ]
  },
  { "title": "Sensor Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 } },
  {
   "title": "Sensor List",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 5 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT category, sensorName, deviceID FROM alert_db.device_table\nWHERE propertyCode = \"${Code}\"\nAND floor = \"${Floor}\" "
    }
   ]
  },
  {
   "title": "Sensor Attribute",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 5 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.device_table\nWHERE deviceID = \"${SensorID}\" \nAND floor = \"${Floor}\""
    }
   ]
  },
  {
   "title": "Message Tag List - $Key",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.message_table\nWHERE deviceID = \"${SensorID}\""
    }
   ]
  },
  { "title": "Floor", "type": "volkovlabs-variable-panel", "gridPos": { "h": 11, "w": 4, "x": 0, "y": 14 } },
  {
   "title": "Image View",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 11, "w": 6, "x": 4, "y": 14 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); color: rgb(247, 218, 100);\" class=\"fr-cell-fixed \">Floorplan :</td>\n            <td style=\"width: 50%; border: rgb(0, 0, 0);\" rowspan=\"2\">\n            <img src=\"/public/img/floorplan/{{variableValue '${Code}'}}/{{variableValue '${Floor}'}}.jpg\"\n                onerror=\"this.src='/public/img/icon/pic-err.svg'\" width=\"150px\"/>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); vertical-align: top;\">\n                {{variableValue '${Floor}'}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); color: rgb(247, 218, 100);\">Area View :</td>\n            <td style=\"width: 50%; border: rgb(0, 0, 0);\" rowspan=\"2\">\n                <img src=\"/public/img/floorplan/{{variableValue '${Code}'}}/{{variableValue '${Area}'}}.jpg\"\n                onerror=\"this.src='/public/img/icon/pic-err.svg'\" width=\"150px\"/>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); vertical-align: top;\">\n                {{variableValue '${Area}'}}<br>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); color: rgb(247, 218, 100);\">Sensor View :</td>\n            <td style=\"width: 50%; border: rgb(0, 0, 0);\" rowspan=\"2\" class=\"fr-cell-handler \">\n                <img src=\"/public/img/floorplan/{{variableValue '${Code}'}}/{{variableValue '${Sensor}'}}.jpg\"\n                onerror=\"this.src='/public/img/icon/pic-err.svg'\" width=\"150px\"/>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 50%; border: rgb(0, 0, 0); vertical-align: top;\">\n                {{variableValue '${Sensor}'}}<br>\n            </td>\n        </tr>\n    </tbody>\n</table>"
   }
  },
  { "title": "Image Upload", "type": "volkovlabs-form-panel", "gridPos": { "h": 7, "w": 7, "x": 10, "y": 14 } },
  {
   "title": "Alarm Attribute",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "dataset": "alert_db",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  { "title": "Export Config File", "type": "volkovlabs-form-panel", "gridPos": { "h": 4, "w": 7, "x": 10, "y": 21 } },
  {
   "title": "User Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current User",
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
     "options": {
      "content": "<table style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 15%; text-align: center; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/user.png\" width=\"18px\"><br>\n            </td>\n            <td style=\"width: 85%; border: rgb(0, 0, 0);\"><span style=\"font-size: 28px;\">${__user.login}</span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; text-align: center; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/case.png\" width=\"18px\"><br>\n            </td>\n            <td style=\"width: 85%; border: rgb(0, 0, 0);\">${__org.name}</td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; text-align: center; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/pin.png\" width=\"18px\"><br>\n            </td>\n            <td style=\"width: 85%; border: rgb(0, 0, 0);\">${Team}</td>\n        </tr>\n    </tbody>\n</table>"
     }
    },
    {
     "title": "User List",
     "type": "table",
     "gridPos": { "h": 7, "w": 11, "x": 5, "y": 26 },
     "targets": [
      { "annotationLimit": 100, "requestType": "orgUsers" }
     ]
    },
    { "title": "User  Property", "type": "volkovlabs-form-panel", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 } }
   ]
  }
 ]
}