{
 "title": "gateway home-en",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Host CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "usage_user_value", "legendFormat": "{{cpu}}" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "average_response_ms_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gateway Configuration",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deviation Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "standard_deviation_ms_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sensor List",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "percent_packet_loss_value", "legendFormat": "__auto" }
   ]
  }
 ]
}