{
 "title": "每月報表",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Team",
    "query": "HGET ${__user.login}@${__org.name} team"
   },
   {
    "name": "Building",
    "query": "SELECT English FROM alert_db.map_table WHERE  team = \"${Team}\""
   },
   {
    "name": "Code",
    "query": "SELECT property_code FROM alert_db.map_table where English in (${Building:doublequote});"
   },
   { "name": "Domain", "query": "GET domain" },
   { "name": "Month", "query": "1,2,3,4,5,6,7,8,9,10,11,12" },
   { "name": "Year", "query": "2024" }
  ]
 },
 "panels": [
  { "title": "大樓", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 } },
  {
   "title": "感測器類別比例",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT sensorType, count(*) total \nFROM alert_db.device_table \nWHERE propertyCode = \"${Code}\" \ngroup by sensorType"
    }
   ]
  },
  {
   "title": "感測器/攝像機 安裝列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.device_table\nwhere propertyCode = \"${Code}\""
    }
   ]
  },
  { "title": "報表年份", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 } },
  { "title": "報表月份", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 } },
  {
   "title": "警報類別統計",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT alarm_type Type, count(*) Total \nFROM alert_db.alert_table \nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \ngroup by alarm_type\n"
    }
   ]
  },
  {
   "title": "警報總數",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" "
    }
   ]
  },
  {
   "title": "結案總數",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \nAND (progress = 3 OR progress = 2)"
    }
   ]
  },
  {
   "title": "關鍵性警報數量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \nAND alarm_priority = \"Critical\""
    }
   ]
  },
  {
   "title": "高優先警報數量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \nAND alarm_priority = \"High\""
    }
   ]
  },
  {
   "title": "誤報警部數量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \nAND progress = 2"
    }
   ]
  },
  { "title": "月報表匯出", "type": "volkovlabs-form-panel", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 } },
  {
   "title": "全月警報統計",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 10 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "\nWITH RECURSIVE DateSeries AS (\n    SELECT DATE_FORMAT(CONCAT('${Year}','-','${Month}','-01'),'%Y-%m-%d') AS alarmDate  \n    UNION ALL  \n    SELECT DATE_ADD(alarmDate, INTERVAL 1 DAY)  \n    FROM DateSeries  \n    WHERE MONTH(alarmDate) = MONTH(DATE_ADD(alarmDate, INTERVAL 1 DAY))  \n      AND YEAR(alarmDate) = YEAR(DATE_ADD(alarmDate, INTERVAL 1 DAY))  \n) \nSELECT date_format(t1.alarmDate, '%m/%d') as alarmDay,\nCOALESCE(t2.critical, 0) as Critical ,COALESCE(t2.high, 0) as High\nFROM (\n\tSELECT alarmDate\n\tFROM DateSeries \n\tWHERE YEAR(alarmDate) = \"${Year}\"\n\t  AND MONTH(alarmDate) = \"${Month}\"\n\tORDER BY alarmDate \n\t) as t1\nleft join(\n\tselect DATE_FORMAT(start_time, '%Y-%m-%d') eventDay, count(*) as cnt,\n\tSUM(CASE WHEN alarm_priority = 'Critical' THEN 1 END) AS critical,\n  SUM(CASE WHEN alarm_priority = 'High' THEN 1 END) AS high \n\tfrom alert_db.alert_table \n\tWHERE\n\t\tyear(start_time) = \"${Year}\"\n\t\tAND month(start_time) = \"${Month}\"\n\t\tAND code = \"${Code}\"\n\tgroup by eventDay\n\t) as t2\n\ton t1.alarmDate = t2.eventDay\n"
    }
   ]
  },
  {
   "title": "關注區域警報統計",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT floor, area , count(*) Total \nFROM alert_db.alert_table \nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \ngroup by floor, area\norder by total DESC"
    }
   ]
  },
  {
   "title": "全月警報列表",
   "type": "table",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT *, date_format(start_time,\"%Y-%m-%d %H:%m:%s\") AlarmTime FROM alert_db.alert_table\nWHERE YEAR(start_time) = \"${Year}\"\nAND MONTH(start_time) = \"${Month}\"\nAND code = \"${Code}\" \nORDER BY start_time ASC"
    }
   ]
  }
 ]
}