{
 "title": "Sensor Status",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Team",
    "query": "HGET ${__user.login}@${__org.name} team"
   },
   {
    "name": "Building",
    "query": "SELECT English FROM alert_db.map_table WHERE  team = \"${Team}\""
   },
   {
    "name": "Code",
    "query": "SELECT property_code FROM alert_db.map_table where english in (${Building:doublequote});"
   },
   {
    "name": "Floor",
    "query": "SELECT DISTINCT floor FROM alert_db.device_table where propertyCode in (${Code:doublequote});"
   }
  ]
 },
 "panels": [
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 21, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Building Name",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 34px; color: rgb(97, 189, 109);\"><strong>${Building}</strong></span>\n"
   }
  },
  { "title": "Floor", "type": "volkovlabs-variable-panel", "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 } },
  {
   "title": "Register Sensor Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.device_table\nWHERE propertyCode = \"$Code\" "
    }
   ]
  },
  {
   "title": "Register Alarm Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.device_table as D\nleft join\n(SELECT * FROM alert_db.message_table) as M\non D.deviceID = M.deviceID\nWHERE propertyCode = \"$Code\" "
    }
   ]
  },
  {
   "title": "Sensor",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 3 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td class=\"border_td\" style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"2\">\n                {{#if (eq category \"cam\")}}\n                <img src=\"/public/img/icon/cam.svg\" width=\"30px\"><br>\n            {{else}}\n                <img src=\"/public/img/icon/iot.svg\" width=\"30px\"><br>\n            {{/if}}\n            </td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/box.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 25%; border: rgb(0, 0, 0);\">{{sensorName}}</td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/Sensor_Source.svg\" width=\"22px\"><br>\n            </td>\n            <td class=\"border_td\" style=\"width: 25%; border: rgb(0, 0, 0);\">\n                {{deviceID}}\n            </td>\n            <td style=\"width: 20%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"2\">\n                {{#if (eq Value Null)}}\n                <img src=\"/public/img/icon/off.svg\" width=\"30px\"><br>\n                {{else}}\n                <img src=\"/public/img/icon/on.svg\" width=\"30px\"><br>\n                {{/if}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/Area_of_Interest.svg\" width=\"22px\"><br>\n            </td>\n            <td style=\"width: 25%; border: rgb(0, 0, 0);\">{{area}}</td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/layer.svg\" width=\"26px\"><br>\n            </td>\n            <td style=\"width: 25%; border: rgb(0, 0, 0);\">{{floor}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.device_table\nWHERE propertyCode = \"$Code\" \nAND floor in (${Floor:doublequote})"
    },
    {
     "expr": "{__name__=~\"probe_.+|data_.+\",code=\"${Code}\",floor=~\"$Floor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}