{
 "title": "Site Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Code",
    "query": "HMGET ${__user.login}@${__org.name} site"
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 28px;\">{{english}}</span>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT english, contact, telno1, telno2 FROM alert_db.map_table \nWHERE property_code = \"${Code}\""
    }
   ]
  },
  {
   "title": "Incidents Analysis by Areas of Interest",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT area, floor, alarm_type, alarm_priority, count(*) 7D FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) and code = \"${Code}\" \ngroup by area, floor, alarm_type, alarm_priority\norder by floor ;"
    },
    {
     "dataset": "alert_db",
     "rawSql": "SELECT area, floor, alarm_type, alarm_priority, count(*) 14D FROM alert_db.alert_table \nwhere start_time between DATE_SUB(NOW(), INTERVAL 14 DAY) and DATE_SUB(NOW(), INTERVAL 7 DAY)\nand code = \"${Code}\" \ngroup by area, floor, alarm_type, alarm_priority\norder by floor ;"
    }
   ]
  },
  {
   "title": "Sensor Status",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 22, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td class=\"border_td\" style=\"width: 15%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"2\">\n              {{#if (eq sensorType 'cam')}}\n                <img src=\"/public/img/icon/cam.svg\" width=\"30px\"><br>\n              {{else}} \n                <img src=\"/public/img/icon/iot.svg\" width=\"30px\"><br>\n              {{/if}}\n              </td>\n            <td style=\"width: 14.9723%; text-align: right; border: rgb(0, 0, 0);\">\n              <img src=\"/public/img/icon/box.svg\" width=\"24px\"><br></td>\n            <td style=\"width: 40%; border: rgb(0, 0, 0);\">{{sensorName}}</td>\n            <td style=\"width: 29.39%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"2\">\n              {{#if (eq Value Null)}} \n              <img src=\"/public/img/icon/off.svg\" width=\"30px\"><br>\n              {{else}} \n              <img src=\"/public/img/icon/on.svg\" width=\"30px\"><br>\n              {{/if}}\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 14.9723%; text-align: right; border: rgb(0, 0, 0);\">\n            <img src=\"/public/img/icon/Area_of_Interest.svg\" width=\"20px\"><br></td>\n            <td class=\"border_td\" style=\"width: 37.3383%; border: rgb(0, 0, 0);\">{{area}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.device_table\nWHERE propertyCode = \"$Code\" "
    },
    {
     "expr": "{__name__=~\"probe_.+|data_.+\",code=\"${Code}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alarm Counts - By Area Of Interests",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 2 },
   "options": {
    "content": "<table class=\"border_table\" style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td class=\"border_td\" style=\"width: 15%; border: rgb(0, 0, 0);\"><span style=\"font-size: 22px;\">\n                {{floor}}</span></td>\n            <td style=\"width: 60%; border: rgb(0, 0, 0);\" colspan=\"2\"><span style=\"font-size: 22px;\">\n                {{area}}</span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/Drop.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 60%; border: rgb(0, 0, 0);\"><span style=\"text-align: start; font-size: 14px;\">Water Leakage </span></td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100); font-size: 20px;\">\n                {{#if (eq alarm_type \"Water_Leakage\")}}\n                    {{#if (eq 7D Null)}}\n                        0\n                    {{else}}\n                        {{7D}}\n                    {{/if}}\n                {{else}}\n                    0\n                {{/if}}\n            </span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/PersonSimpleRun.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 60%; border: rgb(0, 0, 0);\"><span style=\"text-align: start; font-size: 12pt;\"><span style=\"text-align: start; font-size: 14px;\">Intrusion Detected</span></span><br></td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100); font-size: 20px;\">\n                {{#if (eq alarm_type \"Intrusion_Detected\")}}\n                    {{#if (eq 7D Null)}}\n                        0\n                    {{else}}\n                        {{7D}}\n                    {{/if}}\n                {{else}}\n                    0\n                {{/if}}\n            </span></td>\n        </tr>\n        <tr>\n            <td style=\"width: 15%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/BatteryLow.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 60%; border: rgb(0, 0, 0);\"><span style=\"text-align: start; font-size: 14px;\">Battery Low</span><br></td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\"><span style=\"color: rgb(247, 218, 100);\"><span style=\"font-size: 20px;\">\n                {{#if (eq alarm_type \"Battery_Low\")}}\n                    {{7D}}\n                {{else}}\n                    0\n                {{/if}}\n            </span></span></td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Incidents Analysis by Alarm Types",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT alarm_type, count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand code = \"${Code}\"\ngroup by alarm_type"
    }
   ]
  },
  {
   "title": "Alarm Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand code = \"${Code}\""
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 14 },
   "options": {
    "content": "<table style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/Drop.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 65%; border: rgb(0, 0, 0);\">\n                <span style=\"text-align: start; font-size: 12pt;\">Water Leakage </span>\n            </td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100); font-size: 20px;\">\n                    {{#if (eq Water_Leakage Null)}}\n                        0\n                    {{else}}\n                        {{Water_Leakage}}\n                    {{/if}}\n                </span>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/PersonSimpleRun.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 65%; border: rgb(0, 0, 0);\">\n                <span style=\"text-align: start; font-size: 12pt;\"><span style=\"text-align: start; font-size: 12pt;\">Intrusion Detected</span></span><br>\n            </td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100); font-size: 20px;\">\n                    {{#if (eq Intrusion_Detected Null)}}\n                    0\n                    {{else}}\n                    {{Intrusion_Detected}}\n                    {{/if}}\n                </span>\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n                <img src=\"/public/img/icon/BatteryLow.svg\" width=\"24px\" height=\"22px\"><br>\n            </td>\n            <td style=\"width: 65%; border: rgb(0, 0, 0);\">\n                <span style=\"text-align: start; font-size: 12pt;\">Battery Low</span><br>\n            </td>\n            <td style=\"width: 25%; text-align: center; border: rgb(0, 0, 0);\">\n                <span style=\"color: rgb(247, 218, 100);\"><span style=\"font-size: 20px;\">\n                    {{#if (eq Battery_Low Null)}}\n                    0\n                    {{else}}\n                    {{Battery_Low}}\n                    {{/if}}\n                </span></span>\n            </td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Alarm Closed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand progress = '3'\nand code = \"${Code}\""
    }
   ]
  },
  {
   "title": "Critical Alarms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand alarm_priority = 'critical'\nand code = \"${Code}\""
    }
   ]
  },
  {
   "title": "High Priority Alarms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand alarm_priority = 'high'\nand code = \"${Code}\""
    }
   ]
  },
  {
   "title": "Unattended Alarm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) CT FROM alert_db.alert_table \nwhere start_time >= DATE_SUB(NOW(), INTERVAL 7 DAY) \nand progress = '0'\nand code = \"${Code}\""
    }
   ]
  },
  {
   "title": "Sensor Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT count(*) FROM alert_db.device_table\nWHERE propertyCode = \"$Code\" "
    }
   ]
  }
 ]
}