{
 "title": "SweetHeart",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2023-12-31T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "BranchCode",
    "query": "SELECT BranchCode FROM alert_db.demo"
   },
   {
    "name": "Meter",
    "query": "SELECT MeterNumber FROM alert_db.demo\nwhere BranchCode = \"${BranchCode}\""
   },
   { "name": "Year", "query": "2022, 2023, 2024" }
  ]
 },
 "panels": [
  {
   "title": "Average Usage by Branch Code - ${Year}",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "select BranchCode, round(avg(a.TotalUsage),2) Average from\n(\nSELECT\n\tBranchCode, TotalUsage, Amount,\n    month(EndDate) as mon\n FROM alert_db.demo\n where StartDate >= date_format(concat(\"${Year}\", \"-01-01\"), \"%Y-%m-%d\") \n and EndDate <= date_format(concat(\"${Year}\", \"-12-31\"), \"%Y-%m-%d\") \n) a\ngroup by BranchCode\norder by Average desc"
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 } },
  {
   "title": "Usage Average by Month",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "select  \n\tround(avg(a.TotalUsage),2) AverageUsage, \n    round(avg(a.Amount),2) AverageAmount, \n    a.mon \nfrom\n(\nSELECT\n\tBranchCode, TotalUsage, Amount,\n     concat(year(EndDate), '/', month(EndDate)) as mon\n FROM alert_db.demo\n where StartDate >= date_format(concat(\"${Year}\", \"-01-01\"), \"%Y-%m-%d\") \n and EndDate <= date_format(concat(\"${Year}\", \"-12-31\"), \"%Y-%m-%d\")\n and BranchCode = \"${BranchCode}\"\n) a\ngroup by mon"
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 9, "w": 3, "x": 7, "y": 2 } },
  { "title": "Meter Number", "type": "volkovlabs-variable-panel", "gridPos": { "h": 10, "w": 3, "x": 7, "y": 11 } },
  {
   "title": "Usage Contribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "select MeterNumber, round(avg(TotalUsage),2) Average \nFROM alert_db.demo\nwhere StartDate >= '2023-01-01' and EndDate <= '2023-12-31'and BranchCode = \"${BranchCode}\"\ngroup by MeterNumber\n"
    }
   ]
  },
  {
   "title": "by Meter ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "select  round(avg(a.TotalUsage),2) TotalUsage, a.mon from\n(\nSELECT\n\tBranchCode, TotalUsage, Amount,\n     concat(year(EndDate), '/', month(EndDate)) as mon\n FROM alert_db.demo\n where StartDate >= '2023-01-01' and EndDate <= '2023-12-31'and MeterNumber = \"${Meter}\"\n) a\ngroup by mon"
    }
   ]
  }
 ]
}