{
 "title": "User Config",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SelUser" },
   {
    "name": "SelMail",
    "query": "SELECT email FROM alert_db.user WHERE login = \"${SelUser}\""
   },
   {
    "name": "SelTeam",
    "query": "SELECT team FROM alert_db.user WHERE login = \"${SelUser}\""
   },
   {
    "name": "SelGrade",
    "query": "SELECT grade FROM alert_db.user WHERE login = \"${SelUser}\""
   },
   {
    "name": "SelName",
    "query": "SELECT name FROM alert_db.user WHERE login = \"${SelUser}\""
   },
   {
    "name": "CurrGrade",
    "query": "SELECT grade FROM alert_db.user WHERE login = \"${__user.login}\""
   },
   {
    "name": "Building",
    "query": "SELECT english FROM alert_db.map_table"
   }
  ]
 },
 "panels": [
  {
   "title": "User List",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"width: 100%; border-collapse: collapse; border: rgb(0, 0, 0);\">\n    <tbody>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\" rowspan=\"2\">\n              <img src=\"/public/img/icon/login.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 30%; border: rgb(0, 0, 0);\" rowspan=\"2\"><span style=\"font-size: 18px;\">\n              {{login}}</span></td>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n              <img src=\"/public/img/icon/grade.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 30%; border: rgb(0, 0, 0);\">\n            {{#if (eq grade 4)}}\n              System Manager\n            {{/if}}\n            {{#if (eq grade 3)}}\n              Manager\n            {{/if}}\n            {{#if (eq grade 2)}}\n              Team Leader\n            {{/if}}\n            {{#if (eq grade 1)}}\n              Opperator\n            {{/if}}\n            </td>\n            <td style=\"width: 10%; text-align: center; border: rgb(0, 0, 0);\" rowspan=\"2\">\n             {{#if (eq (variableValue '${SelUser}') login)}}\n                    <img src=\"/public/img/icon/check-o-green.svg\" width=\"32px\" height=\"32px\"><br>\n                {{else}}\n                  <!-- http://{{variableValue '${Domain}'}} -->\n                    <a href=\"http://localhost:3000/d/{{variable '{__dashboard.uid}'}}/{{variable '{__dashboard.name}'}}?orgId=variable '{__org.id}'&var-SelUser={{login}}\">\n                    <img src=\"/public/img/icon/check-o-gray.svg\" width=\"32px\" height=\"32px\"></a><br>    \n                {{/if}}\n            img_sel\n            </td>\n        </tr>\n        <tr>\n            <td style=\"width: 10%; text-align: right; border: rgb(0, 0, 0);\">\n              <img src=\"/public/img/icon/team.svg\" width=\"24px\"><br>\n            </td>\n            <td style=\"width: 30%; border: rgb(0, 0, 0);\">{{team}}</td>\n        </tr>\n    </tbody>\n</table>"
   },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.user WHERE grade <= \"${CurrGrade}\""
    }
   ]
  },
  {
   "title": "User Management",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "query": "KEYS *:${__org.name}", "type": "cli" }
   ]
  },
  {
   "title": "Team  (${__org.name})",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dataset": "alert_db",
     "rawSql": "SELECT * FROM alert_db.map_table"
    }
   ]
  }
 ]
}